### ISSUE TITLE
RemoteApp context menu glitches

### ISSUE THREAD

**Issue by tristan-k** [FreeRDP/FreeRDP#2662]
I'm using FreeRDP version 1.2.1-dev (git n/a) on Ubuntu 15.04 and Windows 7 Ultimate KVM with the RemoteApp option. Activating contextual menus results in graphics glichtes which make controlling the applications impossible. Could be a related to https://answers.launchpad.net/winconn/+question/240277 and https://github.com/FreeRDP/FreeRDP/issues/1528.  

```
$ xfreerdp /u:USER /p:PASSWORD /v:127.0.0.1 /app:"||Word2010"
```

Here's a video to illustrate the issue: https://vimeo.com/129231150

**Comment by hardening** [comment]
@tristan-k as said in #1528 you may try last master. Your video is very similar to a bug we have fixed with the polyline graphical order.

**Comment by tristan-k** [comment]
It seems the issue is partly resolved. The glitches are still there but appear more randomly. Some context menus cant be open the first time. I uploaded another video here to illustrate the remaining problems: https://vimeo.com/129290965

**Comment by mjmayer** [comment]
I was experiencing a slightly different video glitch, but its behavior seems similar.  When bringing up context menus I see either a black box if I have no other remote apps running or if I have other apps running I see an overlay of another part of the remoteapp.
https://youtu.be/BogVZPmHftU
shows the glicth. I attempted to compile from source and the problem persists.
$ xfreerdp --version
This is FreeRDP version 1.2.4-dev (git c8731ea)

**Comment by hardening** [comment]
@tristan-k if I'm not mixing up with something else, I think we have some rail associated patch that have been commited recently. Could you test with latest master ?

**Comment by hisaruki** [comment]
I also suffer from the same problem.
I tried the latest master 1.2.5-dev (git fa2c39f).

https://vimeo.com/143782751

**Comment by akallabeth** [comment]
Any update on this one, is this still an issue?

**Comment by akallabeth** [comment]
Could not reproduce issues shown in video in a local test.
Closing as fixed, please reopen if still an issue.
