### ISSUE TITLE
100% cpu when connecting to Win12r2 server

### ISSUE THREAD

**Issue by sphaero** [FreeRDP/FreeRDP#4490]
```
$ WLOG_LEVEL=DEBUG xfreerdp desktop.rdp 
[21:20:55:651] [15188:15188] [DEBUG][com.freerdp.utils] - Registering signal hook...
[21:20:55:654] [15188:15189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[21:20:55:654] [15188:15189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[21:20:55:654] [15188:15189] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[21:20:55:654] [15188:15189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[21:20:55:654] [15188:15189] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: ditza
[21:20:55:661] [15188:15189] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[21:20:55:661] [15188:15189] [DEBUG][com.freerdp.client.x11] - Pointer device: 11
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[21:20:55:662] [15188:15189] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[21:20:55:662] [15188:15189] [INFO][com.freerdp.core.nego] - Detecting if host can be reached locally. - This might take some time.
[21:20:55:662] [15188:15189] [INFO][com.freerdp.core.nego] - To disable auto detection use /gateway-usage-method:direct
[21:20:55:672] [15188:15189] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]
[21:20:55:672] [15188:15189] [ERROR][com.freerdp.core] - getaddrinfo: Name or service not known
GatewayUsername: ***
GatewayDomain:   ***
GatewayPassword: 
[21:21:23:157] [15188:15189] [DEBUG][com.winpr.sspi] - InitSecurityInterfaceExA
[21:21:23:189] [15188:15189] [DEBUG][com.freerdp.core.gateway.rdg] - Out Channel authorization required
[21:21:23:207] [15188:15189] [DEBUG][com.freerdp.core.gateway.rdg] - Out Channel authorization complete
[21:21:23:235] [15188:15189] [DEBUG][com.winpr.sspi] - InitSecurityInterfaceExA
[21:21:23:266] [15188:15189] [DEBUG][com.freerdp.core.gateway.rdg] - In Channel authorization required
[21:21:23:277] [15188:15189] [DEBUG][com.freerdp.core.gateway.rdg] - In Channel authorization complete
```
The program then eats the CPU and nothing happens.

I'm using the remmina next ppa on ubuntu 16.04:
https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next-daily

```$ dpkg -l | grep rdp
ii  freerdp-x11                                     2.0.0~git201803141334-0+remmina201803141401.rf8baeb7.d9be5820~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services
ii  libfreerdp-cache1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                    1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                        1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                         1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-plugins-standard:amd64               2.0.0~git201803141334-0+remmina201803141401.rf8baeb7.d9be5820~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-primitives1.1:amd64                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-utils1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                                amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp1:amd64                               2.0.0~git201803141334-0+remmina201803141401.rf8baeb7.d9be5820~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (library)

$ xfreerdp --buildconfig
This is FreeRDP version 2.0.0-dev2 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=off HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=on WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=on WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wno-format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wno-format-security  -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 5.4.0
Target architecture: x64

```

**Comment by akallabeth** [comment]
Do you use a load balancer?
There is an issue with that, workaround use the ip of the gateway

**Comment by akallabeth** [comment]
For reference, #4476 describes most likely the same issue (gateway connection not really working and getting stuck/abort early)

**Comment by sphaero** [comment]
I've tried setting the ipadres of the gateway I found in the rdp file but then I can't connect:
```
[19:59:44:960] [12574:12575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[19:59:44:960] [12574:12575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[19:59:44:960] [12574:12575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[19:59:44:960] [12574:12575] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: arnaud
[19:59:44:961] [12574:12575] [INFO][com.freerdp.client.x11] - Property 347 does not exist
[19:59:44:961] [12574:12575] [INFO][com.freerdp.core.nego] - Detecting if host can be reached locally. - This might take some time.
[19:59:44:961] [12574:12575] [INFO][com.freerdp.core.nego] - To disable auto detection use /gateway-usage-method:direct
[19:59:44:979] [12574:12575] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]
[19:59:44:979] [12574:12575] [ERROR][com.freerdp.core] - getaddrinfo: Name or service not known
[19:59:44:006] [12574:12575] [ERROR][com.freerdp.core.gateway.tsg] - rpc_connect error!
[19:59:44:006] [12574:12575] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[19:59:44:006] [12574:12575] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[19:59:44:006] [12574:12575] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
```
This is probably the same as running `xfreerdp desktop.rdp /g:80.65.110.58`?

**Comment by akallabeth** [comment]
@sphaero Ah, did miss one hint. Does your RDP file contain a hostname that can only be resolved via internal dns?
So, do you connect via gateway to a system that has a name attached that can not be pinged (unless the supplied IP is used)?

**Comment by sphaero** [comment]
I think it does indeed, it contains an entry `gatewayhostname` which is resolvable and an entry `full address` containing a non-resolvable hostname. An entry called `workspace id` contains the same hostname. Here's the privatized rdp file contents:
```
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:RDBROKER.xxx.xxx
gatewayhostname:s:rdgw.xxx.xxx
workspace id:s:RDBROKER.xxx.xxx
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Desktop_XXX
usbdevicestoredirect:s:*
use multimon:i:1
alternate full address:s:RDBROKER.xxx.xxx
signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayHostname,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:<RANDOM CHARS>
```

**Comment by akallabeth** [comment]
Might be related to #4132

**Comment by akallabeth** [comment]
There have been gateway specific pull requests #4539 and #4547 fixing several issues with gateway usage.
Do any of these fix yours too?

**Comment by sphaero** [comment]
I've tested with a latest build still no luck. However I discovered they have an extra authentication layer in which you need to authorize a session through a mobile app before RDP succeeds. So this is impossible for me to debug. I think you can close this.

**Comment by akallabeth** [comment]
@sphaero Ok, closing.
We've merged redirection and gateway related pulls since then.
Some are still pending, so maybe you're lucky and one of these is squashing your bug too.
