### ISSUE TITLE
[RDPAI] audio lag for mic keeps increasing (>30s and beyond) 

### ISSUE THREAD

**Issue by thecrazyonestherebels** [FreeRDP/FreeRDP#4791]
**Description**
While connecting to Win 10 Desktop Skype call audio lag from mic keeps increasing.

**To Reproduce**
* Compile FreeRDP using WITH_DSP_FFMPEG=ON option on Mac.
* Connect with MacFreeRDP to Win 10 Machine and start Skype for Business (Basic) call.
* Audio lag (delay) keeps increasing immediately ( rate ~2s late/minute )

**Expected behavior**
Lag should not increase but remain consistent.

**Application details**
./client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP --version
This is FreeRDP version 2.0.0-dev4 (b18f9ee86)

* Command line used
```
./client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP /log-level:TRACE /w:1440 /h:860 /clipboard /vc:rdpsnd /dvc:audin /u:`cat /tmp/uname.txt` /g:xxx.xxx /v:zzz.zzz /p:`cat /tmp/tt.txt`
```
* OS version connecting to - Win10 Enterprise

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6

**Comment by akallabeth** [comment]
Does it help to add /gfx:avc444 /network:auto to reduce network bandwidt by 90%?

**Comment by thecrazyonestherebels** [comment]
The delay still keeps increasing even with ``` /gfx:avc444 /network:auto``` setting. FWIW the bandwidth between the machines should not be a problem.

@akallabeth is there some FFMPEG/ AAC setting which needs to be changed for streaming audio please?

**Comment by akallabeth** [comment]
@thecrazyonestherebels The server decides which codec to use. The client can only announce what it supports.
With `/log-level:debug`  you should get some messages informing about the chosen codec (which might change during usage)

**Comment by thecrazyonestherebels** [comment]
@akallabeth Here is the output over 30m call:

```
[13:27:52:973] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:28:01:959] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x01
[13:28:01:959] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - ServerVersion=1, ClientVersion=1
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x02
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - NumFormats 22
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_PCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ALAW nChannels=2 nSamplesPerSec=22050 nBlockAlign=2 wBitsPerSample=8 cbSize=0
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=44100 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=22050 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=32
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=11025 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[13:28:01:020] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=8000 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[13:28:01:084] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x03
[13:28:01:084] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - FramesPerPacket=441 initialFormat=1
[13:28:01:084] [83676:09e53000] [DEBUG][com.freerdp.channels.audin.client] - microphone uses WAVE_FORMAT_ALAW codec
[13:28:01:084] [83676:09e53000] [INFO][com.freerdp.channels.audin.client] - Audio Format WAVE_FORMAT_PCM [channels=2, samples=22050, bits=16]
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:38:22:707] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81c8a0400] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:38:29:781] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:38:31:646] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:38:36:225] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81c8d2e00] Multiple frames in a packet.
[13:38:57:874] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d3cd200] Multiple frames in a packet.
[13:39:04:264] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:39:06:129] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d3cd200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:44:00:067] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:44:02:624] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:44:19:418] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:44:24:986] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:44:30:554] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:45:09:781] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:45:46:939] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81cc26c00] Multiple frames in a packet.
[13:46:29:956] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81e04b800] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:46:59:347] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:47:00:202] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:47:02:064] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81fd5c200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:47:21:830] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:47:23:682] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:47:36:691] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:48:58:828] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:49:00:611] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:49:29:036] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:49:37:424] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d8e2400] Multiple frames in a packet.
[13:50:10:877] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:52:05:113] [83676:9f519380] [DEBUG][com.freerdp.channels.cliprdr.client] - ClientFormatList: numFormats: 5
[13:52:05:179] [83676:09dd0000] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatListResponse
[gsm_ms @ 0x7fe81fd5c200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:52:41:581] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:52:42:209] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:52:52:487] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:52:54:352] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81db05c00] Multiple frames in a packet.
[gsm_ms @ 0x7fe81fd5c200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81db05c00] Multiple frames in a packet.
[gsm_ms @ 0x7fe81db05c00] Multiple frames in a packet.
[13:53:12:931] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:53:15:279] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:53:23:913] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:53:33:306] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81db05c00] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:53:54:349] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:53:57:073] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:54:00:220] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 8000 nAvgBytesPerSec: 1625 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81fd5c200] Multiple frames in a packet.
[13:54:06:848] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 11025 nAvgBytesPerSec: 2239 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[gsm_ms @ 0x7fe81d009200] Multiple frames in a packet.
[13:54:32:436] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 22050 nAvgBytesPerSec: 4478 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
[13:54:33:288] [83676:09d4d000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 1 nSamplesPerSec: 44100 nAvgBytesPerSec: 8957 nBlockAlign: 65 wBitsPerSample: 16 cbSize: 0
```

**Comment by akallabeth** [comment]
Ok, so you use a ffmpeg build without aac support, still the lag is strange.

**Comment by thecrazyonestherebels** [comment]
I tried re-installing brewed FFMPEG with `--with-fdk-aac --with-libvorbis` options, and also installed `lame`. I re-compiled FreeRDP with following options:

`cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" -DWITH_FFMPEG=ON -DWITH_DSP_FFMPEG=ON -DWITH_FAAC=ON -DWITH_LAME=ON -DWITH_FAAD2=ON . && make`

I still see only `WAVE_FORMAT_ALAW` codec getting selected. 

Looking at server announced supported codecs, I see only the following with differing bitrate and channel options: 
* `WAVE_FORMAT_PCM`, 
* `WAVE_FORMAT_ADPCM`, 
* `WAVE_FORMAT_DVI_ADPCM`, 
* `WAVE_FORMAT_ALAW`, & 
* `WAVE_FORMAT_GSM610`.

Is `AAC` codec subset of these, or else is there a way to force server to advertise support for `AAC` too please?

**Comment by akallabeth** [comment]
@thecrazyonestherebels ok, weired, `aac` is the default codec used by windows 10...

**Comment by thecrazyonestherebels** [comment]
It turned out that I was using Windows 10 'N' which even after installing using Media Codec Pack ( both 32 & 64 bit ) doesn't use AAC.

So I did connect to a proper Windows 10 Pro and `AAC` was supported.

Here's the log:

```
[14:42:18:637] [3080:00fde000] [INFO][com.freerdp.codec] - WAVE_FORMAT_PCM:	 wFormatTag: 0x0001 nChannels: 2 nSamplesPerSec: 44100 nAvgBytesPerSec: 12000 nBlockAlign: 4 wBitsPerSample: 16 cbSize: 0
[14:42:23:996] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x01
[14:42:23:997] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - ServerVersion=1, ClientVersion=1
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x02
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - NumFormats 26
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_AAC_MS nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_AAC_MS nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_AAC_MS nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_AAC_MS nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_PCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ALAW nChannels=2 nSamplesPerSec=22050 nBlockAlign=2 wBitsPerSample=8 cbSize=0
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=44100 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=22050 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_ADPCM nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=32
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_DVI_ADPCM nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=11025 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[14:42:23:260] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - wFormatTag=WAVE_FORMAT_GSM610 nChannels=1 nSamplesPerSec=8000 nBlockAlign=65 wBitsPerSample=0 cbSize=2
[14:42:24:520] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - MessageId=0x03
[14:42:24:520] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - FramesPerPacket=441 initialFormat=3
[14:42:24:520] [3080:010e4000] [DEBUG][com.freerdp.channels.audin.client] - microphone uses WAVE_FORMAT_AAC_MS codec
[14:42:24:520] [3080:010e4000] [INFO][com.freerdp.channels.audin.client] - Audio Format WAVE_FORMAT_PCM [channels=2, samples=44100, bits=16]
2018-08-17 14:45:45.714 MacFreeRDP[3080:2174000] Stopping...
[aac @ 0x7fceb0ea6800] Qavg: 226.490
[aac @ 0x7fceb0ea6800] 2 frames left in the queue on closing
2018-08-17 14:45:45.765 MacFreeRDP[3080:2174000] Stopped.
```

However, the delay persists - I was able to estimate many seconds of delay over 7m call.

**Comment by thecrazyonestherebels** [comment]
Now that I've heard with both `ALAW` and `AAC` codecs and seen increasing audio delays, it appears that somehow `FFMPEG` might be responsible for this.

Has anyone seen this behavior or any suggested fixes?

**Comment by akallabeth** [comment]
Looks like this is deeper, can reproduce with `PCM` codec too (which is only pass through from the recording backend).
Looks like we need to adjust the number of samples per packet or something similar for this to always work.
Anyone here that can give a hint in what such values could be?

**Comment by akallabeth** [comment]
@thecrazyonestherebels I think I've found a part of the issue.
Could you post your `/buildconfig` and hardware of the client? It might have to do with (disabled) optimisations and time required to encode the data.

**Comment by sarangkarandikar1** [comment]
Here are the details:

```
./client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP /buildconfig
This is FreeRDP version 2.0.0-dev4 (b18f9ee86)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=OFF WITH_X264=OFF WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations
Compiler:            Clang, 9.1.0.9020039
Target architecture: x64
```

From about this Mac:
```
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
3.3 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Macintosh HD
Intel Iris Graphics 550 1536 MB
```

**Comment by thecrazyonestherebels** [comment]
Here are the details:
```
./client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP /buildconfig
This is FreeRDP version 2.0.0-dev4 (b18f9ee86)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=OFF WITH_X264=OFF WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations
Compiler:            Clang, 9.1.0.9020039
Target architecture: x64
```

From About This Mac:
```
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
3.3 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Macintosh HD
Intel Iris Graphics 550 1536 MB
```

**Comment by akallabeth** [comment]
Ok, that was a dead end :/

**Comment by akallabeth** [comment]
Ok, this is then most likely a configuration issue. (Streaming requires immediate encoded data output, but some codecs have options to compress better if no realtime is required)

**Comment by akallabeth** [comment]
@thecrazyonestherebels Just a question regarding server configuration:
I have not seen the sound/microphone redirection switching codecs so often, and I tested today on my fedora machine without any noticable delay (after hours the delay was still the same and quality excellent, with AAC and GSM codecs as well as PCM)
Since the mac client is in need of testing - Could you check the main loop is not blocked by something? That might cause audio to stop working.

**Comment by hardening** [comment]
I read [here](https://trac.ffmpeg.org/wiki/Encode/AAC) things about `-movflags +faststart` I guess this is the kind of options you're looking for...

**Comment by sarangkarandikar1** [comment]
Made code changes with `movflags` `faststart` options using `libavformat` APIs, still no luck.
@akallabeth don't think the main loop is stalled - using the reset above fixes it.

It still appears to be some sort of `libavcodec` buffers, specifically ones since calling `freerdp_dsp_context_reset()` ever so often also resets the lag to 0.

**Comment by UnoSD** [comment]
I have the same issue running 2.3.2 on Arch Linux (LK 5.11.14-arch1-1), happy to provide logs or to open a separated issue if this is unrelated and for macOS only. Thanks

**Comment by john-okeefe** [comment]
Same issue here on Arch Linux 5.12.6-arch1-1 FreeRDP version 2.3.2.

**Comment by akallabeth** [comment]
@john-okeefe I´ve fixed a few audio (AAC) related things on master, care to try it?

**Comment by john-okeefe** [comment]
@akallabeth Sorry. Been busy. I have it built and will be trying it out through next week.

**Comment by akallabeth** [comment]
@john-okeefe no worries. just curious if #7006 was the reason for the lag you experience.

**Comment by john-okeefe** [comment]
I'm actually having some issues testing this. I usually use it with Remmina and I don't know every flag passed to freerdp. I tested a git build of freerdp today on a phone call and the lag continued, however, everything was much laggier than whatever remmina does with the stable build. I tried passing every flag I thought remmina used including RFX progressive (what I use in Remmina), but everything was still way laggier than on the stable build.

Unfortunately the current git master of Remmina is not building against the current master of freerdp.

**Comment by akallabeth** [comment]
@john-okeefe you might simply install nightly builds and check (they use `FFMPEG` for audio)

**Comment by pasikarkkainen** [comment]
I'm seeing this issue on Fedora 35 with freerdp-2.5.0-1.fc35.x86_64, connecting to Win10 Pro.

Audio lag keeps increasing all the time and it's impossible to discuss for example on Teams call.

But I think the problem is actually on playback side as I'm also hearing others way "too late".. and thus also replying myself too late.

**Comment by akallabeth** [comment]
@pasikarkkainen the fedora build has other issues:
```
WITH_DSP_EXPERIMENTAL=OFF
WITH_EVENTFD_READ_WRITE=1
WITH_FAAC=OFF
WITH_FAAD2=OFF
WITH_FFMPEG=OFF
WITH_GFX_H264=OFF
WITH_GSM=ON
WITH_LAME=ON
WITH_JPEG=ON
WITH_SHADOW_MAC=ON
```
so, this will use bad quality codecs for microphone and high bandwidth (PCM) for playback. When you´re on a line that is maxed out / has packet loss then there will always be some lag.
I´ll check our nightly builder this week, the fedora build needs an update (currently failing)

**Comment by thekingcod** [comment]
please rectivqte my abonment

‫في الاثنين، 14 فبراير 2022 في 8:59 ص تمت كتابة ما يلي بواسطة ‪akallabeth‬‏
***@***.***‬‏>:‬

**Comment by pasikarkkainen** [comment]
@akallabeth Thanks for the reply. I'm using freerdp to connect to a VM running on the same machine (localhost), so I don't think there's any packet loss involved.

The audio lag is so huge that there must be some fundemental problem in the freerdp implementation.. 

I wonder if the problem can be related to the fact of using "pulse" plugin in freerdp, while my fedora desktop is running pipewire (with pulse emulation).. eg is it possibly some kind of glitch between freerdp-pulse talking to pipewire-pulse, and somehow negotiating this huge 5-15 seconds latency ? 

Thanks!

**Comment by akallabeth** [comment]
@pasikarkkainen you can switch the audio backend and it will not make any difference. This sounds like the latency estimation algorithm is running wild.
but wasn´t this issue initially about `microphone` lag? now you´re talking about playback lag?

**Comment by akallabeth** [comment]
@pasikarkkainen It would also be a great help if you could do a (temporary) build from our master branch and check, if the issue is still present.
(just do a `git clone https://github.com/freerdp/freerdp && cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/freerdp -Hfreerdp -Bfreerdp-build && cmake --build freerdp-build --target install` and you have one in `/tmp/freerdp/bin/xfreerdp`. You might need to install a few `devel` packages though)

**Comment by pasikarkkainen** [comment]
@akallabeth ok, thanks, I'll try a build from git. 

At first I thought the problem is "mic lag" but after investigating more the problem seems to be the huge playback lag.. eg. I hear the other people with so much lag/delay that I respond myself way too late, so first it felt like "mic lag", but it's actually playback lag that is the problem..

**Comment by akallabeth** [comment]
@pnowack sadly nothing related. The microphone issue is that the remote end expects exact (implicit as in written to the spec) sample sizes and if the client uses something else, the server uses (implicit) timing information based on these expected sizes.
E.g. If you´re off by 1 then the server will always have not enough/too many samples and just queue them for the next slot, ....

**Comment by akallabeth** [comment]
@firemeteorxx you may be victim of a bad combination of pulse(pipewire?) and freerdp (ALAW not working or badly)
you can try adding `/sound:format:1 /microphone:format:1` to force PCM for playback and recording.

**Comment by firemeteorxx** [comment]
> @firemeteorxx you may be victim of a bad combination of pulse(pipewire?) and freerdp (ALAW not working or badly) you can try adding `/sound:format:1 /microphone:format:1` to force PCM for playback and recording.

Amazing! this trick greatly improved my meeting experience through RDP on both 2.7.0 and 2.9.0 version, for both playback and MIC input.
Thanks for your advice!

**Comment by shmerl** [comment]
I'm hit by this bug as well (Debian testing). I tried rebuilding packages enabling FAAC and FAAD2. But how do I pick them up? By default the client picks ALAW.

Also, setting `/microphone:format:1` picks PCM and that does help a bit in some cases, but for example when recording with VLC it sill starts lagging.

**Comment by shmerl** [comment]
I tried building with that proposed context reset workaround like this:

```
--- a/channels/audin/client/audin_main.c
+++ b/channels/audin/client/audin_main.c
@@ -384,6 +384,18 @@
 	}
 	else
 	{
+		static uint32_t fix_count = 0;
+
+		if (fix_count++ == 512)
+		{
+			fix_count = 0;
+			WLog_Print(audin->log, WLOG_TRACE, "Resetting audin context");
+			if (!freerdp_dsp_context_reset(audin->dsp_context, audin->format))
+			{
+				return ERROR_INTERNAL_ERROR;
+			}
+		}
+
 		if (!freerdp_dsp_encode(audin->dsp_context, format, data, size, audin->data))
 			return ERROR_INTERNAL_ERROR;
 	}
```

That didn't help in my case.

**Comment by akallabeth** [comment]
> I tried building with that proposed context reset workaround like this:
> 
this is outdated information, that specific bug was fixed with latest stable (don´t remember which exact version though)

**Comment by shmerl** [comment]
OK, I'll rebuild it without that patch. But what is the way to select other codecs / formats like FAAC? Or that happens implicitly? Playing around with other indexes in `/format:xxx` didn't work.

**Comment by shmerl** [comment]
OK, just tested a Teams video conference call from Firefox using `format:1` and there were no latency issues. That's something at least.

**Comment by RomanoZumbe** [comment]
Sorry for my ignorance, but where can I provide the format options?

**Comment by TonyHoyle** [comment]
Still happening.. audio lag is hillariously bad.  I tried format:1 and it worked for a minute then the lag started, and within a short period was over 30 seconds.  It makes talking over it completely impossible.  If found alsa was considerably better than pulseaudio (which was so bad I could literally run the mic test in discord and hear my voice a minute later).

**Comment by solenum** [comment]
Any update on this?  I'm close to giving up on rdp entirely.

**Comment by Alladyn47** [comment]
The question is relevant. I would also like to know whether everyone has this problem or only a certain circle of people?
Thank you.

**Comment by akallabeth** [comment]
we can not reproduce this issue so far, so it might be hardware related, have to do with some (unknown to us) network conditions or faac/ffmpeg related (in case you don´t use `format:1` wich is `PCM`)
so without some more details we´re basically stuck.
(that is, if you are using most recent release, otherwise please give specific version information so we can recheck)
